apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: innexar-platform-ingress
  namespace: innexar-platform
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - git.innexar.app
    - sonar.innexar.app
    - artifactory.innexar.app
    - auth.innexar.app
    - grafana.innexar.app
    - monitor.innexar.app
  rules:
  - host: git.innexar.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitlab
            port:
              number: 80
  - host: sonar.innexar.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarqube
            port:
              number: 9000
  - host: artifactory.innexar.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: artifactory
            port:
              number: 8081
  - host: auth.innexar.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080
  - host: grafana.innexar.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
  - host: monitor.innexar.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus
            port:
              number: 9090

